"""
UPAS Core Contracts Package.
Exports all authoritative enums, error types, data classes, lifecycle state machines,
and runtime interfaces.
"""

from upas_core.contracts.enums import (
    ArtifactType,
    AuthPolicy,
    EvidenceType,
    ExecutionStatus,
    ExitCode,
    FinalVerdictState,
    InfraAccess,
    InfraType,
    MigrationClassification,
    MigrationPolicy,
    RiskLevel,
    StepStatus,
    TestLevel,
)
from upas_core.contracts.errors import (
    ApprovalDeniedError,
    BackupFailedError,
    CapabilityMismatchError,
    CommandTimeoutError,
    ConcurrencyBlockedError,
    DigestMismatchError,
    EmergencyHaltError,
    EscalationViolationError,
    IncompatibleVersionError,
    InvalidArtifactError,
    InvalidEvidenceError,
    InvalidStateTransitionError,
    MigrationError,
    PreflightFailedError,
    ProductionAuthError,
    PullFailedError,
    SharedInfraViolationError,
    TestExecutionError,
    UnknownRemoteStateError,
    UPASError,
)
from upas_core.contracts.lifecycle import (
    ChangeLifecycleStateMachine,
    ChangeState,
    DeploymentLifecycleStateMachine,
    DeploymentState,
    ReleaseLifecycleStateMachine,
    ReleaseState,
)
from upas_core.contracts.execution import CommandSpec, ExecutionResult
from upas_core.contracts.security import AuthResult, OIDCClaims, OIDCExpectedConfig
from upas_core.contracts.artifacts import (
    ArtifactDescriptor,
    ArtifactVerificationResult,
    BuilderMetadata,
    SignatureMetadata,
)
from upas_core.contracts.migrations import (
    MigrationResult,
    MigrationSpec,
    RollbackDecision,
)
from upas_core.contracts.testing import (
    EscalationTriggers,
    TestMapEntry,
    TestPlan,
    ZoneSpec,
)
from upas_core.contracts.results import (
    CompatibilityResult,
    GuardResult,
    LockHandle,
    LockResult,
    PreflightResult,
    StepResult,
)
from upas_core.contracts.evidence import (
    ArtifactProvenanceRecord,
    AuthoritativeSourcesRecord,
    CiExecutionRecord,
    EvidenceRecord,
    FinalVerdictRecord,
    GitDagRecord,
    HostLockStateRecord,
    HostRuntimeRecord,
    ProductionAuthorizationRecord,
    ProjectRecord,
    StepEvidenceRecord,
)
from upas_core.contracts.interfaces import (
    ArtifactVerifier,
    CapabilityValidator,
    CommandRunner,
    CompatibilityChecker,
    EvidenceGenerator,
    HostGuard,
    HostLock,
    InfrastructureGuard,
    JtiStore,
    MigrationOrchestrator,
    OIDCVerifier,
    ResourcePreflight,
    RollbackSafetyArbiter,
    TestEscalationEngine,
)

__all__ = [
    # Enums
    "ExitCode",
    "EvidenceType",
    "FinalVerdictState",
    "MigrationClassification",
    "MigrationPolicy",
    "ArtifactType",
    "TestLevel",
    "RiskLevel",
    "InfraType",
    "InfraAccess",
    "AuthPolicy",
    "StepStatus",
    "ExecutionStatus",
    # Errors
    "UPASError",
    "IncompatibleVersionError",
    "ProductionAuthError",
    "ApprovalDeniedError",
    "ConcurrencyBlockedError",
    "DigestMismatchError",
    "PullFailedError",
    "MigrationError",
    "EmergencyHaltError",
    "CommandTimeoutError",
    "UnknownRemoteStateError",
    "TestExecutionError",
    "EscalationViolationError",
    "CapabilityMismatchError",
    "SharedInfraViolationError",
    "InvalidEvidenceError",
    "PreflightFailedError",
    "BackupFailedError",
    "InvalidStateTransitionError",
    "InvalidArtifactError",
    # Lifecycles
    "ChangeState",
    "ReleaseState",
    "DeploymentState",
    "ChangeLifecycleStateMachine",
    "ReleaseLifecycleStateMachine",
    "DeploymentLifecycleStateMachine",
    # Execution
    "CommandSpec",
    "ExecutionResult",
    # Security
    "OIDCClaims",
    "OIDCExpectedConfig",
    "AuthResult",
    # Artifacts
    "BuilderMetadata",
    "SignatureMetadata",
    "ArtifactDescriptor",
    "ArtifactVerificationResult",
    # Migrations
    "MigrationSpec",
    "MigrationResult",
    "RollbackDecision",
    # Testing
    "ZoneSpec",
    "TestMapEntry",
    "EscalationTriggers",
    "TestPlan",
    # Results
    "StepResult",
    "LockHandle",
    "LockResult",
    "PreflightResult",
    "GuardResult",
    "CompatibilityResult",
    # Evidence
    "GitDagRecord",
    "CiExecutionRecord",
    "ArtifactProvenanceRecord",
    "ProductionAuthorizationRecord",
    "HostLockStateRecord",
    "HostRuntimeRecord",
    "AuthoritativeSourcesRecord",
    "ProjectRecord",
    "StepEvidenceRecord",
    "FinalVerdictRecord",
    "EvidenceRecord",
    # Interfaces
    "OIDCVerifier",
    "JtiStore",
    "HostGuard",
    "HostLock",
    "CommandRunner",
    "ArtifactVerifier",
    "MigrationOrchestrator",
    "RollbackSafetyArbiter",
    "TestEscalationEngine",
    "CapabilityValidator",
    "InfrastructureGuard",
    "CompatibilityChecker",
    "ResourcePreflight",
    "EvidenceGenerator",
]
